function sgetline1_2
global Movi xx yy memornot matrix

memornot=memornot+1;

 
 if memornot==1
  e=uicontrol('tag','ddd','style','text',...
            'position',[200 0 200 30],'Backgroundcolor','g','ForegroundColor','k','FontWeight','bold',...
            'string','Vacuoles');   
elseif memornot==0
            e=uicontrol('tag','ddd','style','text',...
            'position',[200 0 200 30],'Backgroundcolor','r','ForegroundColor','k','FontWeight','bold',...
            'string','Active Zones');
        elseif memornot==2
            e=uicontrol('tag','ddd','style','text',...
            'position',[200 0 200 30],'Backgroundcolor','b','ForegroundColor','k','FontWeight','bold',...
            'string','Mitochondria');
  
  elseif memornot==3
     e=uicontrol('tag','ddd','style','text',...
            'position',[200 0 200 30],'Backgroundcolor','y','ForegroundColor','k','FontWeight','bold',...
            'string','Membrane'); 
 elseif memornot>3
       
 set(gcf,'windowbuttonupfcn','sroi03');
  set(gcf,'windowbuttondownfcn','spositions2X');
  
         e=uicontrol('tag','ddd','style','text',...
            'position',[200 0 200 30],'Backgroundcolor','c','ForegroundColor','k','FontWeight','bold',...
            'string','Vesicles'); 
        
        b=uicontrol('tag','ddd','style','pushbutton','callback','swrite',...
            'position',[0 0 100 30],...
            'string','write files');
                b=uicontrol('tag','ddd','style','pushbutton','callback','swrite',...
            'position',[500 0 100 30],...
            'string','write files');

 end;

xx=[];yy=[];